services:
  web:
    build:
      context: ./www
      args:
        RUNTIME: ${RUNTIME}
    image: octorrent_org_www
    container_name: www
    environment:
      NODE_ENV: production
    restart: always
    networks:
      octorrent:
        ipv4_address: 10.0.1.2
    #profiles:
    #  - donotstart

  forums:
    build:
      context: ./forums
      args:
        RUNTIME: ${RUNTIME}
    image: octorrent_org_forums
    container_name: forums
    environment:
      NODE_ENV: production
    restart: always
    networks:
      octorrent:
        ipv4_address: 10.0.1.3
    #profiles:
    #  - donotstart

networks:
  octorrent:
    #external: true
    driver: bridge
    attachable: true
    ipam:
     config:
       - subnet: 10.0.1.0/24
